def hesapmenu()
print("╔════════════════════════╗")
print("║    HESAP MAKİNESİ      ║")
print("║ 1-Toplama              ║")
print("║ 2-Çıkarma              ║")
print("║ 3-Çarpma               ║")
print("║ 4-Bölme                ║")
print("║                        ║")
print("║       SEÇİNİZ          ║")
print("╚════════════════════════╝")

input()
