print("╔══════════════════════════╗")
print("║      SPOR TÜRLERİ        ║")
print("║ 1-Voleybol               ║")
print("║ 2-Futbol                 ║")
print("║ 3-Hentbol                ║")
print("║ 4-Güreş                  ║")
print("║                          ║")
print("║         SEÇİNİZ          ║")
print("╚══════════════════════════╝")

input()
